services:
  db:
    image: mysql
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  server1:
    build:
      context: ./server1
      dockerfile: Dockerfile
    container_name: server1
    restart: unless-stopped
    environment:
      JDBC_URL: jdbc:mysql://db/author_db?user=root&password=admin
    depends_on:
      - db
  server2:
    build:
      context: ./server2
      dockerfile: Dockerfile
    container_name: server2
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
  server3:
    build:
      context: ./server3
      dockerfile: Dockerfile
    container_name: server3
    restart: unless-stopped
    ports:
      - 8081:80
    depends_on:
      - server1
      - server2
    environment:
      SERVER1_URL: http://server1:8080/server1/authors
      SERVER2_URL: http://server2:8080/server2/books
